### ISSUE TITLE
Unable to subscribe to pointcloud

### ISSUE THREAD

**Issue by Choco83** [ros-perception/pointcloud_to_laserscan#12]
Hello!

I am using ROS Kinetic and facing a weird issue here. Unable to subscribe to my pointcloud using your package. It works fine with simulation, but not with bag or real lidar.
I have tried every possible combination of trick I could think of, including changing the cpp file to subscribe to topic directly, sampling pointcloud, remapping and God knows what. Still unable to subscribe to my Velodyne. Can anyone suggest what might be the problem. I will appreciate any help in this regard.

**Comment by tfoote** [comment]
Following our [support guidelines](http://wiki.ros.org/Support) please ask for help on http://answers.ros.org

When you do please make sure to provide enough information to reproduce your issue so that we can help you.
