### ISSUE TITLE
Error pluginlib::InvalidXMLException

### ISSUE THREAD

**Issue by soutieslak** [ros-perception/pointcloud_to_laserscan#13]
When running a the following command: roslaunch pointcloud_to_laserscan sample_node.launch

I get this error:

process[pointcloud_to_laserscan-16]: started with pid [28156]
terminate called after throwing an instance of 'pluginlib::InvalidXMLException'
  what():  XML Document has no Root Element.  This likely means the XML is malformed or missing.

I am running ROS Lunar. Could anybody assist me?

**Comment by paulbovbel** [comment]
That's bizarre - I'm not having the same error when running from binaries. Are you building from source?

**Comment by soutieslak** [comment]
Hi Paul! Yes I am. This is what I tried, maybe you can point out a step I am missing, or where I went wrong. 

1. git clone in my catkin_ws/src
2. catkin_make 
3. source devel/setup.sh
4. roslaunch pointcloud_to_laserscan sample_node.launch

And then I get that issue when starting the node... 

My LiDAR node runs fine, noticed this error happens with it running/or not running.

Am I missing a setting that I should set?

I first came about this error when I tried using the scanse/sweep-ros launch file called "sweep2scan.launch which calls the pointcloud_to_laserscan package. This is when I first got the error, and then tested it out seperatley and got the same issue. (here is the scanse git repository:  https://github.com/scanse/sweepers )

Any help would be great man!

**Comment by tfoote** [comment]
@soutieslak What platform are you running on? What version of pointcloud_to_laserscan and pluginlib are you running? Can you test from binary packages only w/o your workspace?

**Comment by soutieslak** [comment]
@tfoote thank your for the reply. I am using ROS Lunar, on Ubuntu 17.04

I am not sure which version of pointcloud_to_laserscan I am using, but when I initially got the error, I removed it (sudo apt-get remove ros-lunar-pointcloud-to-laserscan) and then I added it again (sudo apt-get install ros-lunar-pointcloud-to-laserscan) and when that still gave the same error, I then performed a "git clone" of this version here. The package.xml file reads V1.4.0

The pluginlib package.xml file reads V1.11.0

When I call the package without being in my workspace I get the same error.

Thanks again for your replies and assistance, I appreciate your help

**Comment by soutieslak** [comment]
When bypassing the launch file and just trying to run the pointcloud_to_laserscan on the pointcloud_to_laserscan_node I get the same error:

![image](https://user-images.githubusercontent.com/5350054/34975478-90404912-fa9a-11e7-8dfe-17ef3af1d514.png)

Is it possible that my pluginlib is damaged/corrupt?

**Comment by soutieslak** [comment]
I just setup another PC with ROS, same config as mine and it works there... So that means there is no issue with the package... must be something weird with my PC's setup... Nooooooooo!!!! 

Any suggestions as to what it could possibly be? Would like to try avoid formatting... Is there a know "fix ros install" that you guys maybe know about?

**Comment by mikaelarguedas** [comment]
> same config as mine and it works there...

Can you confirm what version of pluginlib you're running on both machines?
`apt-cache show ros-lunar-pluginlib | grep Version`

The last released version 1.11.2 includes a fix to workaround the issue of unreleated malformed xml files throwing errors.

Another issue we faced (not sure if it's related) is that tinyxml2 on Ubuntu Zesty is broken so we had to release a patched version in the ROS repositories. Can you please make sure that you have the version of tinyxml2 distributed by ROS (4.0.1-2zesty and **not** 4.0.1-1):
```
$ apt-cache show libtinyxml2-dev | grep Version
Version: 4.0.1-2zesty # this is the ROS version
```

**Comment by soutieslak** [comment]
I will have a look on the other machine now now, but for now this is what it looks like on the machine giving the error:

![image](https://user-images.githubusercontent.com/5350054/35027340-ddf4eabe-fb58-11e7-8932-8a95cc60aa88.png)

Is it normal that it lists 2 versions of both?

Edit: Here is the screenshot from the PC who's is working
![image](https://user-images.githubusercontent.com/5350054/35028866-ccaf3ce8-fb60-11e7-817f-7d96d3251745.png)

So the pluginlib versions differ, how can I try "downgrade" from 1.11.2 (the version on the PC that is giving this error) back to 1.11.0 (the version not giving the error) to see if that is the issue?

**Comment by tfoote** [comment]
@soutieslak please copy and paste console output contents instead of screenshotting. That way text is copyable, searchable, and not potentially blurry.

**Comment by soutieslak** [comment]
Thanks @tfoote, I will do so in the future

**Comment by mikaelarguedas** [comment]
@soutieslak It looks like your issue is due to the fact that gmapping 3.9 is installed on one machine and not the other (see https://github.com/ros-perception/slam_gmapping/pull/56 for more details).

Can you confirm that removing gmapping package fixes your issue?
```
sudo apt remove ros-lunar-gmapping
```  

Though pluginlib 1.11.2 should fix the issue...
The error message should still be displayed but `pointcloud_to_laserscan` should not crash. Can you please confirm that you still have `Aborted (core dumped)` on the console of the machine that's failing?

On my side I have something like this:
```
root@830f21cbbf76:/# rosrun pointcloud_to_laserscan pointcloud_to_laserscan_node 
[ERROR] [1516468010.020242179]: Skipped loading plugin with error: XML Document '/opt/ros/lunar/share/gmapping/nodelet_plugins.xml' has no Root Element. This likely means the XML is malformed or missing..
[ INFO] [1516468010.021229441]: Initializing nodelet with 8 worker threads.
```
Note that `pointcould_to_laserscan` is running correctly after printing the error message

**Comment by mikaelarguedas** [comment]
I believe this can be closed now that https://github.com/ros-perception/slam_gmapping/pull/56 has been merged ans released

**Comment by paulbovbel** [comment]
Thanks!
