### ISSUE TITLE
Check for range_max is missing

### ISSUE THREAD

**Issue by moooeeeep** [ros-perception/pointcloud_to_laserscan#19]
After the minimum range is checked [here](https://github.com/ros-perception/pointcloud_to_laserscan/blob/lunar-devel/src/pointcloud_to_laserscan_nodelet.cpp#L215
), the point is dropped when the value is smaller than `range_min_`. 

Another check should be performed to also skip readings beyond the maximum range (threshold determined by the parameter `range_max`).

Example:

    [...]
    else if  (range > range_max_) {
        NODELET_DEBUG("rejected for range %f above maximum value %f. Point: (%f, %f, %f)", range, range_max_, *iter_x, *iter_y, *iter_z);
        continue;
    }
    [...]

Unfortunately I can't make a PR right now. Maybe I will get to that later.

**Comment by paulbovbel** [comment]
Thanks for the report!
