### ISSUE TITLE
is 'angle_increment' vertical or horizontal resolution??

### ISSUE THREAD

**Issue by coco721** [ros-perception/pointcloud_to_laserscan#24]
hi,
i noticed there is a 'angle_increment' parameter. is 'angle_increment' for input data or output data?  And if this for input data(which mean set this parameter by checking lidar's hardware manual), vertical resolution or horizontal  resolution this refer to?

many thanks

**Comment by paulbovbel** [comment]
angle_increment determines how many 'slots' the output laserscan has, so you can think of it as the polar resolution.
