### ISSUE TITLE
What's the difference between Laserscan and pointcloud

### ISSUE THREAD

**Issue by tanrye** [ros-perception/pointcloud_to_laserscan#26]
What's the difference between Laserscan and pointcloud？

**Comment by reinzor** [comment]
- http://docs.ros.org/api/sensor_msgs/html/msg/LaserScan.html (range representation)
- http://docs.ros.org/api/sensor_msgs/html/msg/PointCloud2.html (point representation)

**Comment by paulbovbel** [comment]
@tanrye, please direct general questions towards answers.ros.org (http://wiki.ros.org/Support)
