### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by furushchev** [ros-perception/pointcloud_to_laserscan#31]
It looks the recent update on this repository is not yet released. (e.g. https://github.com/ros-perception/pointcloud_to_laserscan/pull/28 )

@paulbovbel 
Could you please release on kinetic and later distros if there is no problem?

**Comment by reinzor** [comment]
@paulbovbel , could you create a release?

**Comment by paulbovbel** [comment]
Thanks for the reminder, I've released for melodic.

kinetic is based on the indigo-devel branch. I'm happy to take a backport PR.
