### ISSUE TITLE
scan topic is empty ( topic not published yet)

### ISSUE THREAD

**Issue by walid19** [ros-perception/pointcloud_to_laserscan#32]
I am trying to convert Pointcloud2 msg  to laser scan, I mapped the input topic in the launch file . the out laser scan topic is empty ?.

**Comment by kungfrank** [comment]
Hello, I have the same problem. Did you solve it?

**Comment by walid19** [comment]
Hi not yet I am still struggling, plz if you fix it let me know

**Comment by hynkis** [comment]
1. Try to run this command in terminal at first.
rosrun pointcloud_to_laserscan pointcloud_to_laserscan_node cloud_in:="your pointcloud topic"
and subscribe topic "/scan" (/scan is the default publish topic).

2. If it works, then it means pointcloud_to_laserscan package works and you need to change the parameters in the example launch file (simple_node.launch). In my case, "scan_time" parameter was too big(default 0.33, mine was 0.033). You can check the right parameters by 'rostopic echo' the message "/scan" when you run the 'rosrun' command above.

**Comment by walid19** [comment]
Thank you so much it works for me now :)
