### ISSUE TITLE
Documented default values for angle_min and angle_max are wrong

### ISSUE THREAD

**Issue by mdepp** [ros-perception/pointcloud_to_laserscan#36]
In the documentation, it says that `angle_min` defaults to -pi/2 and `angle_max` defaults to pi/2. But they actually default to -pi and pi respectively.

**Comment by luxi-huang** [comment]
Hello I am facing the same problem. Have you solve it?

**Comment by hidmic** [comment]
Good catch @mdepp. Would you be willing to contribute a fix?

**Comment by paulbovbel** [comment]
Fixed in https://github.com/ros-perception/pointcloud_to_laserscan/commit/be047d2a075ff946699ba1397b96d054244b967e
