### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Timple** [ros-perception/pointcloud_to_laserscan#38]
Would you mind releasing this package also for the newest distribution ROS Noetic? :)

**Comment by Timple** [comment]
I preformed a pre-release test on noetic. Compilation and test wise everything seems in order!
`Summary: 1 tests, 0 errors, 0 failures, 0 skipped`

**Comment by SteveMacenski** [comment]
@paulbovbel @tfoote, can either of you release?

**Comment by paulbovbel** [comment]
Done! https://github.com/ros/rosdistro/pull/25342

**Comment by SteveMacenski** [comment]
@paulbovbel this is also a relatively small package - I'd be willing to add this to my list of things to maintain / track that would help at all.
