### ISSUE TITLE
Foxy release

### ISSUE THREAD

**Issue by mdtoom** [ros-perception/pointcloud_to_laserscan#41]
Is it possible to make a foxy release of pointcloud_to_laserscan?

**Comment by paulbovbel** [comment]
Tagging @hidmic since he did the ROS2 port and is a maintainer - would he be willing to cut the Foxy (and probably Rolling) release?

**Comment by hidmic** [comment]
Thanks for the bump @paulbovbel. I'll take care.

**Comment by clalancette** [comment]
I've now given @hidmic write permissions both to this repository and to https://github.com/ros2-gbp/pointcloud_to_laserscan-release so he can do releases.

**Comment by hidmic** [comment]
Done https://github.com/ros/rosdistro/pull/25849.

**Comment by paulbovbel** [comment]
Thanks!
