### ISSUE TITLE
pointcloud to laserscan is all .inf

### ISSUE THREAD

**Issue by chopin1998** [ros-perception/pointcloud_to_laserscan#43]
i write a a code publish sensor data (pointcloud) to /cloud_in 

i can view the points in rviz2, seems no problem

then run:
**`ros2 run pointcloud_to_laserscan pointcloud_to_laserscan_node --ros-args -p angle_min:=-1.0471975511965976 -p angle_max:=1.0471975511965976`**

a /scan topic is created, but all data is - .inf

how to resolve the problem?

my ros2 version is foxy

Thank you very much!

**Comment by chopin1998** [comment]
ok, it's the problem on parameters: min_height and max_height

**Comment by jpgvl** [comment]
@chopin1998 sorry, how did you fix it? Why were the min_height and max_height the problem? I am facing the same issue.
