### ISSUE TITLE
which version is your ros2

### ISSUE THREAD

**Issue by Wuxinxiaoshifu** [ros-perception/pointcloud_to_laserscan#47]
when i was cmaking, errors occurred. 
     Could not find a package configuration file provided by "message_filters" with any of the following names:
    message_filtersConfig.cmake
    message_filters-config.cmake

then i think is my version of ros2,  my ros2 version is  bouncy, can you tell me which version is your ros2

**Comment by hidmic** [comment]
@Wuxinxiaoshifu indeed `message_filters` does not seem to have been ported to Bouncy (see [distribution.yaml](https://github.com/ros/rosdistro/blob/master/bouncy/distribution.yaml)). At any rate, Bouncy reached EOL in July 2019. I recommend you switch to a more recent version (such as Dashing or Foxy). 

I'll close this ticket now. Feel free to reopen if need be.
