### ISSUE TITLE
ROS2 and ROS error

### ISSUE THREAD

**Issue by chengm0-0** [ros-perception/pointcloud_to_laserscan#51]
Hi, when i download your programm and try to catkin_make it, I get the following error:
This workspace contains non-catkin packages in it, and catkin cannot build a non-homogeneous workspace without isolation.  Try the 'catkin_make_isolated' command instead. 
I thought that maybe your program is in ROS2, but my environment is ROS. Do you have the versions in ROS?
thanks:)

**Comment by tfoote** [comment]
If you're using the default branch that's for ROS 2 as per the name foxy-devel. YOu will want to check out the appropriate branch for your rosdistro. You can find the appropriate branch for each distro in rosindex: https://index.ros.org/p/pointcloud_to_laserscan/github-ros-perception-pointcloud_to_laserscan/#noetic under the VCS Version label. 

If you need more help please ask your question on answers.ros.org this it a bug tracker where we try to track issues in the code that need to be fixed.
