### ISSUE TITLE
Galactic and rolling release

### ISSUE THREAD

**Issue by mdtoom** [ros-perception/pointcloud_to_laserscan#59]
Is it possible to make a galactic and rolling release for `pointcloud_to_laserscan`?
Just the normal foxy package works fine on galactic for us, but it is easier to not have it included in a workspace.

**Comment by hidmic** [comment]
Sure. I'll try to squeeze a release next week.

**Comment by hidmic** [comment]
Well, it didn't happen. Sorry for the delay. Releases are out. See https://github.com/ros/rosdistro/pull/31018 and https://github.com/ros/rosdistro/pull/31019.
