### ISSUE TITLE
pointcloud_to_laserscan in ROS1 and Python

### ISSUE THREAD

**Issue by healthyertech** [ros-perception/pointcloud_to_laserscan#66]
Hi,
for a project I am working on I would need to convert a PointCloud2 message to LaserScan message. I am developing my code in ROS1 (melodic) and Python and I would like to make this procedure fully working inside my Python code. I would ask if there exist a version of this package working in ROS1 and maybe if it already exists or it will be provided a version of this package for Python too.
Thanks in advance for the answer.
Best Regards.

**Comment by paulbovbel** [comment]
I believe that is left as an exercise for the reader.
