### ISSUE TITLE
Error while launching sample_node.launch with ros1

### ISSUE THREAD

**Issue by WafaAbid1** [ros-perception/pointcloud_to_laserscan#78]
[ERROR] [1673513936.186537404]: Skipped loading plugin with error: XML Document '/opt/ros/noetic/share/tf2_server/tf2_server_test_nodelets.xml' has no Root Element. This likely means the XML is malformed or missing..

**Comment by paulbovbel** [comment]
This is a setup problem, please work through ROS1 tutorials.
