### ISSUE TITLE
Is there an example how to use it?

### ISSUE THREAD

**Issue by rsc9421** [ros-perception/pointcloud_to_laserscan#79]
It will be very useful to have an example to use in ros2

**Comment by schreiterjp** [comment]
Hi, 

Basic usage in Ros2: 

clone package into ros_ws/src and build package with colcon
or 
run apt install ros-humble-pointcloud-to-laserscan

```source /opt/ros/<distro>/setup.bash```
```cd <ros_ws>```
```source install/setup.bash```

```ros2 launch pointcloud_to_laserscan sample_pointcloud_to_laserscan_launch.py```

**Comment by paulbovbel** [comment]
https://github.com/ros-perception/pointcloud_to_laserscan/tree/rolling/launch
