### ISSUE TITLE
Resolution problems

### ISSUE THREAD

**Issue by DragosCr** [ros-perception/pointcloud_to_laserscan#8]
Hi,
I am using the library (pointcloud_to laserscan) and I successfully made it work and communicate with the other nodes.My problem is that I have very few points and my laser data in rviz. The depthimage_to_laserscan library is doing the same thing, but the "resolution" of the output is a lot better(they are just a lot of points in the laser line). I want to ask if they are any arguments or parameters that can change the resolution of the output laser scan from the library. Any kind of help or idea will be very helpful.
![depthimage_to_laserscan](https://cloud.githubusercontent.com/assets/24623741/21288644/eae1d532-c488-11e6-9beb-4d9ba7d1e3c1.png)
![poincloud_to_laserscan](https://cloud.githubusercontent.com/assets/24623741/21288645/eae45f8c-c488-11e6-953f-70aafa467e76.png)

**Comment by paulbovbel** [comment]
Please post general questions on ROS Answers in the future.

The `angle_increment` parameter will increase the resolution of the laserscan. However, if your pointcloud points aren't dense enough, you'll end with a lot of 'inf' rays in the output sensor_msgs/LaserScan.
