### ISSUE TITLE
How to project LaserScan to the floor in the robot coordination

### ISSUE THREAD

**Issue by Blacook** [ros-perception/pointcloud_to_laserscan#83]
I would like to project PointClouds as LaserScans to the floor with a tilted LiDAR
But in this module, the Clouds must be projected to the same plane as the bottom of the LiDAR.
How can I project Clouds to the floor with the tilted LiDAR.

**Comment by AngeLoGa** [comment]
Doesn't target_frame parameter exist for this purpose?
