### ISSUE TITLE
laser_scan become very short

### ISSUE THREAD

**Issue by hcws** [ros-perception/pointcloud_to_laserscan#84]
**this is my cloud points** 

![Selection_095](https://github.com/ros-perception/pointcloud_to_laserscan/assets/28213814/e21d2157-55fc-4540-a4e3-a51e9b937b3b)

 **this is my lase_scan**

![Selection_096](https://github.com/ros-perception/pointcloud_to_laserscan/assets/28213814/383d10eb-291a-4c4a-9a86-0a33abe396b6)

**this is my point_to_scan.launch file**

![Selection_097](https://github.com/ros-perception/pointcloud_to_laserscan/assets/28213814/d1406855-153d-4935-be02-d90b75db4d25)

**Is there someone who know,why?**

**Comment by TZECHIN6** [comment]
As its laser scan, make sure your centre level lidar beam is hitting the far target (I guess the reason is the your centre-level beam is hitting the cloest object)

**Comment by paulbovbel** [comment]
as @TZECHIN6 highlights, min_height is the problem.
