### ISSUE TITLE
ROS1 Noetic - Process has died

### ISSUE THREAD

**Issue by bcodesnow** [ros-perception/pointcloud_to_laserscan#91]
![image](https://github.com/ros-perception/pointcloud_to_laserscan/assets/50692300/08d90048-4c50-4184-ae57-e6b153ad31c5)

Cloud comes from a 3D Lidar (Livox Mid-360) If using a realsense camera with the same config the node wont crash.

**Comment by bcodesnow** [comment]
Has anyone an idea why this might happen? 

```
[pointcloud_to_laserscan-1] process has died [pid 37920, exit code -11, cmd /opt/ros/noetic/lib/pointcloud_to_laserscan/pointcloud_to_laserscan_node cloud_in:=/livox/lidar scan:=/livox/scan __name:=pointcloud_to_laserscan __log:=/home/ros/.ros/log/048401e2-3acc-11ef-9cd2-2166689de681/pointcloud_to_laserscan-1.log].
log file: /home/ros/.ros/log/048401e2-3acc-11ef-9cd2-2166689de681/pointcloud_to_laserscan-1*.log

```

Logs are empty.

**Comment by bcodesnow** [comment]
Solved.. The problem was the apt package. Compiled the 1.4.1 version from source on the same machine, it works without issues.

**Comment by tdcsu** [comment]
thanks
