### ISSUE TITLE
Jazzy support

### ISSUE THREAD

**Issue by EnzoGhisoni** [ros-perception/pointcloud_to_laserscan#92]
Is it plan to port this package to Jazzy?

**Comment by paulbovbel** [comment]
As far as I can tell, this package is already being built for Jazzy (https://build.ros2.org/job/Jbin_uN64__pointcloud_to_laserscan__ubuntu_noble_amd64__binary/lastBuild/). Is it not present in the apt repos?

**Comment by EnzoGhisoni** [comment]
You are right, my bad.
It didn't see the jazzy branch so I was not sure.
Thanks for the fast answer.
